networks:
  dejima-net: null
services:
  p1-postgres:
    container_name: p1-postgres
    environment:
    - PEER_NAME=p1
    image: ekayim/dejima-postgres:latest
    networks:
    - dejima-net
    ports:
    - 54321:5432
    volumes:
    - ./postgres/conf/postgresql.conf:/etc/postgresql.conf
    - ./postgres/init:/docker-entrypoint-initdb.d/
    - ./postgres/bx_setup:/etc/bx_setup
  p1-proxy:
    container_name: p1-proxy
    depends_on:
    - p1-postgres
    environment:
    - PEER_NAME=p1
    - DEJIMA_CONFIG_YAML=/proxy/dejima_setting.yml
    - CC_METHOD=r2w
    image: ekayim/dejima-proxy:latest
    networks:
    - dejima-net
    ports:
    - 8001:8000
    stdin_open: true
    tty: true
    volumes:
    - ./proxy:/proxy
  p2-postgres:
    container_name: p2-postgres
    environment:
    - PEER_NAME=p2
    image: ekayim/dejima-postgres:latest
    networks:
    - dejima-net
    ports:
    - 54322:5432
    volumes:
    - ./postgres/conf/postgresql.conf:/etc/postgresql.conf
    - ./postgres/init:/docker-entrypoint-initdb.d/
    - ./postgres/bx_setup:/etc/bx_setup
  p2-proxy:
    container_name: p2-proxy
    depends_on:
    - p2-postgres
    environment:
    - PEER_NAME=p2
    - DEJIMA_CONFIG_YAML=/proxy/dejima_setting.yml
    - CC_METHOD=r2w
    image: ekayim/dejima-proxy:latest
    networks:
    - dejima-net
    stdin_open: true
    tty: true
    volumes:
    - ./proxy:/proxy
  p3-postgres:
    container_name: p3-postgres
    environment:
    - PEER_NAME=p3
    image: ekayim/dejima-postgres:latest
    networks:
    - dejima-net
    ports:
    - 54323:5432
    volumes:
    - ./postgres/conf/postgresql.conf:/etc/postgresql.conf
    - ./postgres/init:/docker-entrypoint-initdb.d/
    - ./postgres/bx_setup:/etc/bx_setup
  p3-proxy:
    container_name: p3-proxy
    depends_on:
    - p3-postgres
    environment:
    - PEER_NAME=p3
    - DEJIMA_CONFIG_YAML=/proxy/dejima_setting.yml
    - CC_METHOD=r2w
    image: ekayim/dejima-proxy:latest
    networks:
    - dejima-net
    stdin_open: true
    tty: true
    volumes:
    - ./proxy:/proxy
  p4-postgres:
    container_name: p4-postgres
    environment:
    - PEER_NAME=p4
    image: ekayim/dejima-postgres:latest
    networks:
    - dejima-net
    ports:
    - 54324:5432
    volumes:
    - ./postgres/conf/postgresql.conf:/etc/postgresql.conf
    - ./postgres/init:/docker-entrypoint-initdb.d/
    - ./postgres/bx_setup:/etc/bx_setup
  p4-proxy:
    container_name: p4-proxy
    depends_on:
    - p4-postgres
    environment:
    - PEER_NAME=p4
    - DEJIMA_CONFIG_YAML=/proxy/dejima_setting.yml
    - CC_METHOD=r2w
    image: ekayim/dejima-proxy:latest
    networks:
    - dejima-net
    ports:
    - 8004:8000
    stdin_open: true
    tty: true
    volumes:
    - ./proxy:/proxy
version: '3'
