version: '3'
services:
  bank-postgres:
    image: ekayim/dejima-postgres:latest
    container_name: bank-postgres
    ports:
      - 54321:5432
    networks:
      - dejima-net
    environment:
      - PEER_NAME=bank
    volumes:
      - ./docker-postgres/conf/postgresql.conf:/etc/postgresql.conf
      - ./docker-postgres/init:/docker-entrypoint-initdb.d/
      - ./docker-postgres/bx_setup:/etc/bx_setup


  bank-proxy:
    image: ekayim/dejima-proxy:latest
    container_name: bank-proxy
    volumes:
      - ./proxy:/proxy
    ports:
      - 8001:8000
    environment:
      - PEER_NAME=bank
      - DEJIMA_CONFIG_YAML=/proxy/dejima_setting.yml
    networks:
      - dejima-net
    depends_on:
      - bank-postgres
    stdin_open: true
    tty: true

  government-postgres:
    image: ekayim/dejima-postgres:latest
    container_name: government-postgres
    ports:
      - 54322:5432
    networks:
      - dejima-net
    environment:
      - PEER_NAME=government
    volumes:
      - ./docker-postgres/conf/postgresql.conf:/etc/postgresql.conf
      - ./docker-postgres/init:/docker-entrypoint-initdb.d/
      - ./docker-postgres/bx_setup:/etc/bx_setup


  government-proxy:
    image: ekayim/dejima-proxy:latest
    container_name: government-proxy
    volumes:
      - ./proxy:/proxy
    ports:
      - 8002:8000
    environment:
      - PEER_NAME=government
      - DEJIMA_CONFIG_YAML=/proxy/dejima_setting.yml
    networks:
      - dejima-net
    depends_on:
      - government-postgres
    stdin_open: true
    tty: true
    
  insurance-postgres:
    image: ekayim/dejima-postgres:latest
    container_name: insurance-postgres
    ports:
      - 54323:5432
    networks:
      - dejima-net
    environment:
      - PEER_NAME=insurance
    volumes:
      - ./docker-postgres/conf/postgresql.conf:/etc/postgresql.conf
      - ./docker-postgres/init:/docker-entrypoint-initdb.d/
      - ./docker-postgres/bx_setup:/etc/bx_setup


  insurance-proxy:
    image: ekayim/dejima-proxy:latest
    container_name: insurance-proxy
    volumes:
      - ./proxy:/proxy
    ports:
      - 8003:8000
    environment:
      - PEER_NAME=insurance
      - DEJIMA_CONFIG_YAML=/proxy/dejima_setting.yml
    networks:
      - dejima-net
    depends_on:
      - insurance-postgres
    stdin_open: true
    tty: true

networks:
  dejima-net:
