version: '3'
services:
  bank-postgres:
    image: ekayim/dejima-postgres:latest
    container_name: bank-postgres
    ports:
      - 54321:5432
    networks:
      - dejima-net
    environment:
      - PEER_NAME=bank
    volumes:
      - ./docker-postgres/conf/postgresql.conf:/etc/postgresql.conf
      - ./docker-postgres/init:/docker-entrypoint-initdb.d/
      - ./docker-postgres/bx_setup:/etc/bx_setup


  bank-proxy:
    image: ekayim/dejima-proxy:latest
    container_name: bank-proxy
    volumes:
      - ./proxy:/proxy
    ports:
      - 8001:8000
    environment:
      - PEER_NAME=bank
      - POSTGRES_HOST=bank-postgres.dejima-net
      - DEJIMA_CONFIG_YAML=/proxy/dejima_setting.yml
    networks:
      - dejima-net
    depends_on:
      - bank-postgres

networks:
  dejima-net:
